import type { Metadata } from "next";
import { Inter, Public_Sans } from "next/font/google";
import "./globals.css";
import { TanstackProvider } from "./TanstackProvider";
import { CookiesProvider } from "next-client-cookies/server";

const sans = Public_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={sans.className}>
        <CookiesProvider>
          <TanstackProvider>{children}</TanstackProvider>
        </CookiesProvider>
      </body>
    </html>
  );
}
